# Generated by Django 2.2 on 2020-10-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.CharField(default='5', max_length=100),
        ),
    ]
