# Generated by Django 2.2 on 2020-10-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20201012_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
