from django.urls import path
from . import views
urlpatterns = [
    path('', views.index,name='index'),
    path('contact/', views.contact,name='contact'),
    path('singup/', views.singup,name='singup'),
    path('login/', views.login,name='login'),
    path('shop/', views.shop,name='shop'),
    path('verify_otp/', views.verify_otp,name='verify_otp'),
    path('logout/', views.logout,name='logout'),
    path('enter_email',views.enter_email,name='enter_email'),
    path('update_password/',views.update_password,name='update_password'),
    path('change_password/',views.change_password,name='change_password'),
    path('add_product/',views.add_product,name='add_product'),
    path('seller_index/',views.seller_index,name='seller_index'),
    path('view_product/',views.view_product,name='view_product'),
    path('product_detal/<int:pk>/',views.product_detal,name='product_detal'),
    path('product_stock/<int:pk>/',views.product_stock,name='product_stock'),
    path('unavailable_product/',views.unavailable_product,name='unavailable_product'),
    path('edit_product/<int:pk>/',views.edit_product,name='edit_product'),
    path('delete_product/<int:pk>/',views.delete_product,name='delete_product'),
    path('men/',views.men,name='men'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('mywishlist/',views.mywishlist,name='mywishlist'),
    path('remove_wishlist/<int:pk>/',views.remove_wishlist,name='remove_wishlist'),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name='add_to_cart'),
    path('remove_cart/<int:pk>/',views.remove_cart,name='remove_cart'),
    path('mycart/',views.mycart,name='mycart'),
    path('review/<int:pk>/',views.review,name='review'),
    path('callback/',views.callback,name='callback'),
    path('pay/',views.initiate_payment,name='make_payment'),
    path('validate_username/',views.validate_username,name='validate_username'),
]

